// vue-project/src/views/IphoneDetails.vue
<template>
  <div>
    <!-- Buttons -->
    <button @click="goBack">Back to iPhones</button>
    <button id="deleteButton" @click="deleteIphone">Delete iPhone</button>
    <button @click="editIphone">Edit iPhone</button>

    <!-- iPhone Details -->
    <h1>iPhone Details</h1>
    <div id="iphoneDetails">
      <p><strong>ID:</strong> {{ iphone.id }}</p>
      <p><strong>Full Name:</strong> {{ iphone.model }}</p>
      <p><strong>Release Year:</strong> {{ iphone.releaseYear }}</p>
    </div>

    <!-- Edit iPhone Modal -->
    <div v-if="showEditModal" class="modal">
      <div class="modal-content">
        <span class="close-button" @click="showEditModal = false">&times;</span>
        <h2>Edit iPhone</h2>
        <table>
          <tr>
            <td>Model:</td>
            <td><input v-model="editModel" placeholder="iPhone Model" /></td>
          </tr>
          <tr>
            <td>Release Year:</td>
            <td><input type="number" v-model="editYear" placeholder="Release Year" /></td>
          </tr>
        </table>
        <button @click="confirmEdit">Save Changes</button>
      </div>
    </div>

    <!-- Components Section -->
    <h3>Components</h3>
    <button @click="fetchComponents">Show Components</button>
    <button @click="addComponent">Add Component</button>

    <!-- Components List -->
    <ul v-if="showComponents">
      <li v-for="component in components" :key="component.id" @click="viewComponent(component)">
        <strong> {{ component.type }}</strong> 
      </li>
    </ul>

    <!-- Add Component Modal -->
    <div v-if="showAddComponentModal" class="modal">
      <div class="modal-content">
        <span class="close-button" @click="showAddComponentModal = false">&times;</span>
        <h2>Add New Component</h2>
        <table>
          <tr>
            <td>Name:</td>
            <td><input v-model="newComponentName" placeholder="Component Name" /></td>
          </tr>
          <tr>
            <td>Type:</td>
            <td><input v-model="newComponentType" placeholder="Component Type" /></td>
          </tr>
          <tr>
            <td>Specs:</td>
            <td><input v-model="newComponentSpecs" placeholder="Component Specs" /></td>
          </tr>
        </table>
        <button @click="confirmAddComponent">Add Component</button>
      </div>
    </div>

    <!-- Component Details Modal -->
    <div v-if="showComponentDetailModal" class="modal">
      <div class="modal-content">
        <span class="close-button" @click="showComponentDetailModal = false">&times;</span>
        <h2>Component Details</h2>
        <p><strong>ID:</strong> {{ selectedComponent.id }}</p>
        <p><strong>Name:</strong> {{ selectedComponent.name }}</p>
        <p><strong>Type:</strong> {{ selectedComponent.type }}</p>
        <p><strong>Specs:</strong> {{ selectedComponent.specs }}</p>
        <button @click="editComponent(selectedComponent)">Edit Component</button>
        <button @click="deleteComponent(selectedComponent)" style="background-color: red;">Delete Component</button>
      </div>
    </div>

    <!-- Edit Component Modal -->
    <div v-if="showEditComponentModal" class="modal">
      <div class="modal-content">
        <span class="close-button" @click="showEditComponentModal = false">&times;</span>
        <h2>Edit Component</h2>
        <table>
          <tr>
            <td>Name:</td>
            <td><input v-model="editComponentName" /></td>
          </tr>
          <tr>
            <td>Type:</td>
            <td><input v-model="editComponentType" /></td>
          </tr>
          <tr>
            <td>Specs:</td>
            <td><input v-model="editComponentSpecs" /></td>
          </tr>
        </table>
        <button @click="confirmEditComponent">Save Changes</button>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import axios from 'axios'

// Routing
const route = useRoute()
const router = useRouter()
const iphoneId = route.params.id

// Reactive state
const iphone = ref({})
const components = ref([])
const showComponents = ref(false)

// Edit iPhone modal
const showEditModal = ref(false)
const editModel = ref('')
const editYear = ref('')

// Add Component modal
const showAddComponentModal = ref(false)
const newComponentName = ref('')
const newComponentType = ref('')
const newComponentSpecs = ref('')

// Component details modal
const showComponentDetailModal = ref(false)
const selectedComponent = ref({})

// Edit Component modal
const showEditComponentModal = ref(false)
const editComponentName = ref('')
const editComponentType = ref('')
const editComponentSpecs = ref('')

// Fetch iPhone details
const fetchIphone = async () => {
  try {
    const res = await axios.get(`http://localhost:8080/iphones/${iphoneId}`)
    iphone.value = res.data
  } catch (err) {
    console.error('Failed to fetch iPhone:', err)
    alert('Failed to load iPhone details.')
  }
}

// Fetch components for this iPhone
const fetchComponents = async () => {
  try {
    const res = await axios.get(`http://localhost:8080/components/iphone/${iphoneId}`)
    components.value = res.data || []
    showComponents.value = true
  } catch (err) {
    console.error('Failed to fetch components:', err)
    alert('Failed to fetch components.')
  }
}

// Navigation
const goBack = () => router.push('/')

// Delete iPhone
const deleteIphone = async () => {
  if (confirm('Are you sure you want to delete this iPhone?')) {
    try {
      await axios.delete(`http://localhost:8080/iphones/${iphoneId}`)
      alert('iPhone deleted successfully!')
      router.push('/')
    } catch (err) {
      console.error(err)
      alert('Failed to delete iPhone.')
    }
  }
}

// Edit iPhone
const editIphone = () => {
  editModel.value = iphone.value.model
  editYear.value = iphone.value.releaseYear
  showEditModal.value = true
}

const confirmEdit = async () => {
  try {
    const updatedData = {
      model: editModel.value,
      releaseYear: parseInt(editYear.value)
    }
    await axios.put(`http://localhost:8080/iphones/${iphoneId}`, updatedData)
    iphone.value.model = editModel.value
    iphone.value.releaseYear = parseInt(editYear.value)
    showEditModal.value = false
    alert('iPhone updated successfully!')
  } catch (err) {
    console.error(err)
    alert('Failed to update iPhone.')
  }
}

// Add Component
const addComponent = () => {
  newComponentName.value = ''
  newComponentType.value = ''
  newComponentSpecs.value = ''
  showAddComponentModal.value = true
}

const confirmAddComponent = async () => {
  if (!newComponentName.value.trim() || !newComponentType.value.trim() || !newComponentSpecs.value.trim()) {
    alert('Please fill in all fields.')
    return
  }

  try {
    const componentData = {
      name: newComponentName.value.trim(),
      type: newComponentType.value.trim(),
      specs: newComponentSpecs.value.trim(),
      iphone_id: parseInt(iphoneId)
    }
    const res = await axios.post(`http://localhost:8080/components`, componentData)
    components.value.push(res.data)
    showAddComponentModal.value = false
    alert('Component added successfully!')
  } catch (err) {
    console.error(err)
    alert('Failed to add component.')
  }
}

// View Component Details
const viewComponent = (component) => {
  selectedComponent.value = { ...component }
  showComponentDetailModal.value = true
}

// Edit Component
const editComponent = (component) => {
  editComponentName.value = component.name
  editComponentType.value = component.type
  editComponentSpecs.value = component.specs
  selectedComponent.value = { ...component }
  showComponentDetailModal.value = false
  showEditComponentModal.value = true
}

// Confirm Edit Component
const confirmEditComponent = async () => {
  try {
    const updatedData = {
      name: editComponentName.value.trim(),
      type: editComponentType.value.trim(),
      specs: editComponentSpecs.value.trim(),
      iphone_id: parseInt(iphoneId)
    }
    const res = await axios.put(`http://localhost:8080/components/${selectedComponent.value.id}`, updatedData)
    const idx = components.value.findIndex(c => c.id === selectedComponent.value.id)
    if (idx !== -1) components.value[idx] = { ...res.data }
    selectedComponent.value = { ...res.data }
    showEditComponentModal.value = false
    alert('Component updated successfully!')
  } catch (err) {
    console.error(err)
    alert('Failed to update component.')
  }
}

// Delete Component
const deleteComponent = async (component) => {
  if (confirm('Are you sure you want to delete this component?')) {
    try {
      await axios.delete(`http://localhost:8080/components/${component.id}`)
      components.value = components.value.filter(c => c.id !== component.id)
      showComponentDetailModal.value = false
      alert('Component deleted successfully!')
    } catch (err) {
      console.error(err)
      alert('Failed to delete component.')
    }
  }
}

onMounted(fetchIphone)
</script>

<style scoped>
/* Modal styles */
.modal {
  display: block;
  position: fixed;
  z-index: 1000;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: rgba(0,0,0,0.5);
}
.modal-content {
  background-color: #fefefe;
  margin: 100px auto;
  padding: 20px;
  border: 1px solid #888;
  width: 300px;
  border-radius: 8px;
  box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}
.close-button {
  float: right;
  font-size: 24px;
  font-weight: bold;
  cursor: pointer;
  color: #aaa;
}
.close-button:hover { color: #000; }
button { margin: 4px; padding: 8px 12px; border-radius: 4px; cursor: pointer; }
#deleteButton { background-color: red; color: white; }
ul { list-style: none; padding: 0; }
li { padding: 8px; border: 1px solid #ddd; margin: 4px 0; cursor: pointer; }
#iphoneDetails { background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1px solid #dee2e6; margin: 15px 0; }
input { width: 100%; padding: 6px; margin: 2px 0; }
</style>

// react/src/components/IphoneDetails.jsx
import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";

export default function IphoneDetails() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [iphone, setIphone] = useState(null);
  const [components, setComponents] = useState([]);
  const [showComponents, setShowComponents] = useState(false);
  const [selectedComponent, setSelectedComponent] = useState(null);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showComponentModal, setShowComponentModal] = useState(false);
  const [componentMode, setComponentMode] = useState("add"); // "add" or "edit"
  const [editedIphone, setEditedIphone] = useState({ model: "", releaseYear: "" });
  const [editedComponent, setEditedComponent] = useState({ type: "", specs: "" });
  const [error, setError] = useState(null);

  // Fetch iPhone details from backend
  useEffect(() => {
    fetch(`http://localhost:8080/iphones/${id}`)
      .then(res => res.json())
      .then(data => {
        setIphone(data);
        setEditedIphone({ model: data.model, releaseYear: data.releaseYear });
      })
      .catch(err => setError(err.message));
  }, [id]);

  // Fetch components for this iPhone
  const fetchComponents = () => {
    fetch(`http://localhost:8080/components/iphone/${id}`)
      .then(res => res.json())
      .then(data => setComponents(data))
      .catch(err => setError(err.message));
  };

  const handleShowComponents = () => {
    if (!showComponents) fetchComponents();
    setShowComponents(!showComponents);
    setSelectedComponent(null);
  };

  // iPhone Edit
  const handleEditSubmit = (e) => {
    e.preventDefault();
    if (!editedIphone.model.trim()) return setError("Model is required");
    if (!editedIphone.releaseYear || editedIphone.releaseYear < 2000 || editedIphone.releaseYear > new Date().getFullYear())
      return setError("Enter a valid release year");

    fetch(`http://localhost:8080/iphones/${id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(editedIphone),
    })
      .then(res => res.json())
      .then(updated => {
        setIphone(updated);
        setShowEditModal(false);
        setError(null);
      })
      .catch(err => setError(err.message));
  };

  // Delete iPhone
  const handleDeleteIphone = () => {
    if (window.confirm("Are you sure you want to delete this iPhone?")) {
      fetch(`http://localhost:8080/iphones/${id}`, { method: "DELETE" })
        .then(res => {
          if (!res.ok) throw new Error("Failed to delete iPhone");
          navigate("/");
        })
        .catch(err => setError(err.message));
    }
  };

  // Add/Edit Component
  const handleComponentSubmit = (e) => {
    e.preventDefault();
    if (!editedComponent.type.trim()) return setError("Type is required");

    const method = componentMode === "add" ? "POST" : "PUT";
    const url = componentMode === "add" 
                ? `http://localhost:8080/components`
                : `http://localhost:8080/components/${selectedComponent.id}`;

    const body = componentMode === "add"
                 ? { ...editedComponent, iphone_id: id }
                 : editedComponent;

    fetch(url, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    })
      .then(res => res.json())
      .then(() => {
        fetchComponents();
        setShowComponentModal(false);
        setSelectedComponent(null);
        setEditedComponent({ type: "", specs: "" });
        setError(null);
      })
      .catch(err => setError(err.message));
  };

  // Delete Component
  const handleDeleteComponent = (compId) => {
    if (window.confirm("Are you sure you want to delete this component?")) {
      fetch(`http://localhost:8080/components/${compId}`, { method: "DELETE" })
        .then(() => {
          fetchComponents();
          setSelectedComponent(null);
        })
        .catch(err => setError(err.message));
    }
  };

  if (error) return (
    <div style={{ padding: "20px" }}>
      <p style={{ color: "red", backgroundColor: "#ffe6e6", padding: "10px", borderRadius: "4px" }}>
        Error: {error}
      </p>
      <button onClick={() => setError(null)}>Clear Error</button>
    </div>
  );

  if (!iphone) return (
    <div style={{ padding: "20px" }}>
      <p>Loading...</p>
    </div>
  );

  return (
    <div style={{ padding: "20px", fontFamily: "Arial, sans-serif", textAlign: "left", backgroundColor: "#f8f9fa", minHeight: "100vh" }}>
      <h1 style={{ marginBottom: "20px" }}>iPhone Details</h1>

      {/* Top Buttons */}
      <div style={{ marginBottom: "20px", display: "flex", gap: "10px" }}>
        <button onClick={() => navigate("/")} style={{ backgroundColor: "#28a745", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", cursor: "pointer" }}>
          ← Back
        </button>
        <button onClick={() => setShowEditModal(true)} style={{ backgroundColor: "#28a745", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", cursor: "pointer" }}>
          Edit
        </button>
        <button onClick={handleDeleteIphone} style={{ marginLeft: "auto", backgroundColor: "#dc3545", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", cursor: "pointer" }}>
          Delete
        </button>
      </div>

      {/* iPhone Details Box */}
      <div style={{ backgroundColor: "white", padding: "20px", borderRadius: "8px", boxShadow: "0 2px 4px rgba(0,0,0,0.1)", marginBottom: "20px", border: "1px solid #e0e0e0" }}>
        <p><strong>Model:</strong> {iphone.model}</p>
        <p><strong>ID:</strong> {iphone.id}</p>
        <p><strong>Release Year:</strong> {iphone.releaseYear}</p>
      </div>

      {/* Components Buttons */}
      <div style={{ display: "flex", gap: "10px", marginBottom: "10px" }}>
        <button onClick={handleShowComponents} style={{ padding: "8px 16px", backgroundColor: "#28a745", color: "white", border: "none", borderRadius: "4px", cursor: "pointer" }}>
          {showComponents ? "Hide Components" : "Show Components"}
        </button>
        <button onClick={() => { setComponentMode("add"); setEditedComponent({ type: "", specs: "" }); setShowComponentModal(true); }} style={{ padding: "8px 16px", backgroundColor: "#28a745", color: "white", border: "none", borderRadius: "4px", cursor: "pointer" }}>
          Add Component
        </button>
      </div>

      {/* Components List */}
      {showComponents && (
        <ul style={{ listStyle: "none", padding: 0 }}>
          {components.length === 0 ? <li>No components for this iPhone.</li> : components.map(c => (
            <li key={c.id} style={{ cursor: "pointer", marginBottom: "8px", padding: "10px", backgroundColor: selectedComponent?.id === c.id ? "#e3f2fd" : "#f8f9fa", border: "1px solid #dee2e6", borderRadius: "4px" }}
              onClick={() => setSelectedComponent(selectedComponent?.id === c.id ? null : c)}
            >
              <strong>{c.type}</strong>
              {selectedComponent?.id === c.id && (
                <div style={{ marginTop: "10px" }}>
                  <p><strong>Specs:</strong> {c.specs || "N/A"}</p>
                  <div style={{ display: "flex", gap: "10px", marginTop: "10px" }}>
                    <button onClick={(e) => { e.stopPropagation(); setComponentMode("edit"); setEditedComponent({ type: c.type, specs: c.specs }); setShowComponentModal(true); }} style={{ padding: "6px 12px", backgroundColor: "#28a745", color: "white", border: "none", borderRadius: "4px", cursor: "pointer" }}>
                      Edit
                    </button>
                    <button onClick={(e) => { e.stopPropagation(); handleDeleteComponent(c.id); }} style={{ padding: "6px 12px", backgroundColor: "#dc3545", color: "white", border: "none", borderRadius: "4px", cursor: "pointer" }}>
                      Delete
                    </button>
                  </div>
                </div>
              )}
            </li>
          ))}
        </ul>
      )}

      {/* iPhone Edit Modal */}
      {showEditModal && (
        <div style={{ position: "fixed", top: 0, left: 0, width: "100%", height: "100%", backgroundColor: "rgba(0,0,0,0.5)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000 }}
          onClick={e => { if (e.target === e.currentTarget) setShowEditModal(false); }}>
          <div style={{ backgroundColor: "white", padding: "30px", borderRadius: "8px", boxShadow: "0 4px 6px rgba(0,0,0,0.1)", maxWidth: "500px", width: "90%", position: "relative" }}>
            <span onClick={() => setShowEditModal(false)} style={{ position: "absolute", top: "10px", right: "15px", fontSize: "28px", fontWeight: "bold", cursor: "pointer", color: "#aaa" }}>×</span>
            <h2>Edit iPhone</h2>
            <div>
              <div style={{ marginBottom: "15px" }}>
                <label style={{ display: "block", marginBottom: "5px", fontWeight: "bold" }}>Model:</label>
                <input type="text" value={editedIphone.model} onChange={e => setEditedIphone(prev => ({ ...prev, model: e.target.value }))} style={{ width: "100%", padding: "8px", border: "1px solid #ddd", borderRadius: "4px" }} />
              </div>
              <div style={{ marginBottom: "20px" }}>
                <label style={{ display: "block", marginBottom: "5px", fontWeight: "bold" }}>Release Year:</label>
                <input type="number" value={editedIphone.releaseYear} onChange={e => setEditedIphone(prev => ({ ...prev, releaseYear: e.target.value }))} min="2000" max={new Date().getFullYear()} style={{ width: "100%", padding: "8px", border: "1px solid #ddd", borderRadius: "4px" }} />
              </div>
              <div style={{ textAlign: "right" }}>
                <button onClick={() => setShowEditModal(false)} style={{ backgroundColor: "#6c757d", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", marginRight: "10px", cursor: "pointer" }}>Cancel</button>
                <button onClick={handleEditSubmit} style={{ backgroundColor: "#28a745", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", cursor: "pointer" }}>Save</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Component Add/Edit Modal */}
      {showComponentModal && (
        <div style={{ position: "fixed", top: 0, left: 0, width: "100%", height: "100%", backgroundColor: "rgba(0,0,0,0.5)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000 }}
          onClick={e => { if (e.target === e.currentTarget) setShowComponentModal(false); }}>
          <div style={{ backgroundColor: "white", padding: "30px", borderRadius: "8px", boxShadow: "0 4px 6px rgba(0,0,0,0.1)", maxWidth: "500px", width: "90%", position: "relative" }}>
            <span onClick={() => setShowComponentModal(false)} style={{ position: "absolute", top: "10px", right: "15px", fontSize: "28px", fontWeight: "bold", cursor: "pointer", color: "#aaa" }}>×</span>
            <h2>{componentMode === "add" ? "Add Component" : "Edit Component"}</h2>
            <div>
              <div style={{ marginBottom: "15px" }}>
                <label style={{ display: "block", marginBottom: "5px", fontWeight: "bold" }}>Type:</label>
                <input type="text" value={editedComponent.type} onChange={e => setEditedComponent(prev => ({ ...prev, type: e.target.value }))} style={{ width: "100%", padding: "8px", border: "1px solid #ddd", borderRadius: "4px" }} />
              </div>
              <div style={{ marginBottom: "20px" }}>
                <label style={{ display: "block", marginBottom: "5px", fontWeight: "bold" }}>Specs:</label>
                <input type="text" value={editedComponent.specs} onChange={e => setEditedComponent(prev => ({ ...prev, specs: e.target.value }))} style={{ width: "100%", padding: "8px", border: "1px solid #ddd", borderRadius: "4px" }} />
              </div>
              <div style={{ textAlign: "right" }}>
                <button onClick={() => setShowComponentModal(false)} style={{ backgroundColor: "#6c757d", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", marginRight: "10px", cursor: "pointer" }}>Cancel</button>
                <button onClick={handleComponentSubmit} style={{ backgroundColor: "#28a745", color: "white", padding: "8px 16px", border: "none", borderRadius: "4px", cursor: "pointer" }}>{componentMode === "add" ? "Add" : "Save"}</button>
              </div>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
